# Generated by Django 4.1.2 on 2022-10-09 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='foro',
            new_name='foto',
        ),
    ]
